# Generated by Django 3.2.7 on 2021-09-07 22:29

import blog.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('published', blog.models.PublishedManager()),
            ],
        ),
    ]
